name: CD - Deploy Server (self-hosted)

on:
  workflows_run:
    workflow : ["CI - Verification HTML"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted,deploy, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to web directory
        run: |
          sudo mkdir -p /var/www/eval-cicd
          sudo rsync -av --delete ./ /var/www/eval-cicd/
